package JavaCollections;

public class AboutCollections {
	//1. FRAMEwORK: TO STORE AND MANIPULATE GROUP OF OBJECTS
	//2. OPERATIONS: SEARCH,INSERTION, DELETION, MANIPULATION, SORTING
	//3. INTERFACES: LIST,SET,QUEUE,DEQUE
	//4. CLASSES:ARRAYLIST, VECTOR, LINKEDLIST, HASHSET, PRIORITYQUEUE, ETC

}
